### ISSUE TITLE
Looping error when trying to give items

### ISSUE THREAD

**Issue by pcktfox** [Rx4Byte/SunHaven#7]
Trying to add DLC items via the !give command often results in a looping error that eventually forces me to close the game via closing BepInEx itself:

[Error  : Unity Log] UnityEngine.AddressableAssets.InvalidKeyException: Exception of type 'UnityEngine.AddressableAssets.InvalidKeyException' was thrown. No Location found for Key=10924

I say often because it doesn't seem consistent? On one character I was able to give myself multiple DLC chests without issue, while on another I could give myself the two Kickstarter pets, but no chests.

ETA: Saw a comment on the mod page on Nexus that someone is having the same issue as me (black screen when changing areas after using the !give command) when giving themselves a base game item (coal).

**Comment by WovenViper** [comment]
I've been having this issue as well. I just left a comment on nexus, but I figured I should leave one here too. I'm getting the same looping error and black screen. I tested it with just trying to give myself a small amount of gold (100) and it happened the same as with anything else. I haven't personally tested with DLC items so I don't know about the consistency issues, but it seems the black screen happens with everything.

**Comment by Misaki412** [comment]
Hello, I've been having the same issue. I installed Command Extension and was so happy at first because it worked really fine. Even when I gave myself a Glorite Sword. But then out of nowhere when I was trying to give myself a lotus, I didn't get the item and when I changed area I found myself stuck on black screen and the game won't shut down unless I stop it in the tasks manager. Looked all over internet to find a solution but it seems the bug wasn't fixed even though so many people reported it, and it's really unfortunate since it's important to my gameplay. It's a good mod having so much potential, but I'm starting to worry since the last complain was in July.
